# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TableauMetricqueryserviceTypesV1Entitlement(BaseModel):
    """
    TableauMetricqueryserviceTypesV1Entitlement
    """ # noqa: E501
    entitlement_type: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["entitlement_type", "enabled"]

    @field_validator('entitlement_type')
    def entitlement_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ENTITLEMENT_TYPE_UNSPECIFIED', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_CONSUMPTION', 'ENTITLEMENT_TYPE_PULSE_DIGEST_CONTROL', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_SCALE', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_INSIGHTS', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_GAI']):
            raise ValueError("must be one of enum values ('ENTITLEMENT_TYPE_UNSPECIFIED', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_CONSUMPTION', 'ENTITLEMENT_TYPE_PULSE_DIGEST_CONTROL', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_SCALE', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_INSIGHTS', 'ENTITLEMENT_TYPE_PULSE_PREMIUM_GAI')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceTypesV1Entitlement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceTypesV1Entitlement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entitlement_type": obj.get("entitlement_type"),
            "enabled": obj.get("enabled")
        })
        return _obj


