# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_authn_v1_oidc_config import TableauAuthnV1OidcConfig
from typing import Optional, Set
from typing_extensions import Self

class TableauAuthnV1AuthConfiguration(BaseModel):
    """
    TableauAuthnV1AuthConfiguration
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Authentication instance ID.")
    created_at: Optional[StrictStr] = Field(default=None, description="Date and time stamp of when the authentication instance was configured.")
    updated_at: Optional[StrictStr] = Field(default=None, description="Date and time stamp of when the authentication instance was updated.")
    auth_type: Optional[StrictStr] = None
    iframed_idp_enabled: Optional[StrictBool] = Field(default=None, description="Allows the identity provider (IdP) to authenticate inside of an iFrame. The IdP must disable clickjack protection to allow iFrame presentation. Default value is 'false'.")
    oidc: Optional[TableauAuthnV1OidcConfig] = None
    __properties: ClassVar[List[str]] = ["id", "created_at", "updated_at", "auth_type", "iframed_idp_enabled", "oidc"]

    @field_validator('auth_type')
    def auth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['OIDC']):
            raise ValueError("must be one of enum values ('OIDC')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauAuthnV1AuthConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of oidc
        if self.oidc:
            _dict['oidc'] = self.oidc.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauAuthnV1AuthConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "auth_type": obj.get("auth_type"),
            "iframed_idp_enabled": obj.get("iframed_idp_enabled"),
            "oidc": TableauAuthnV1OidcConfig.from_dict(obj["oidc"]) if obj.get("oidc") is not None else None
        })
        return _obj


