# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_pulse_insightsservice_v1_error import TableauPulseInsightsserviceV1Error
from openapi_client.models.tableau_pulse_insightsservice_v1_insight_response import TableauPulseInsightsserviceV1InsightResponse
from openapi_client.models.tableau_pulse_insightsservice_v1_summary_response import TableauPulseInsightsserviceV1SummaryResponse
from typing import Optional, Set
from typing_extensions import Self

class TableauPulseInsightsserviceV1InsightGroup(BaseModel):
    """
    TableauPulseInsightsserviceV1InsightGroup
    """ # noqa: E501
    type: Optional[StrictStr] = None
    insights: Optional[List[TableauPulseInsightsserviceV1InsightResponse]] = None
    summaries: Optional[List[TableauPulseInsightsserviceV1SummaryResponse]] = None
    error: Optional[TableauPulseInsightsserviceV1Error] = None
    __properties: ClassVar[List[str]] = ["type", "insights", "summaries", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauPulseInsightsserviceV1InsightGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in insights (list)
        _items = []
        if self.insights:
            for _item_insights in self.insights:
                if _item_insights:
                    _items.append(_item_insights.to_dict())
            _dict['insights'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in summaries (list)
        _items = []
        if self.summaries:
            for _item_summaries in self.summaries:
                if _item_summaries:
                    _items.append(_item_summaries.to_dict())
            _dict['summaries'] = _items
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauPulseInsightsserviceV1InsightGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "insights": [TableauPulseInsightsserviceV1InsightResponse.from_dict(_item) for _item in obj["insights"]] if obj.get("insights") is not None else None,
            "summaries": [TableauPulseInsightsserviceV1SummaryResponse.from_dict(_item) for _item in obj["summaries"]] if obj.get("summaries") is not None else None,
            "error": TableauPulseInsightsserviceV1Error.from_dict(obj["error"]) if obj.get("error") is not None else None
        })
        return _obj


