# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TableauPulseSubscriptionserviceTypesV1MetricGroupingPreferences(BaseModel):
    """
    TableauPulseSubscriptionserviceTypesV1MetricGroupingPreferences
    """ # noqa: E501
    group_by: Optional[StrictStr] = None
    sort_order: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["group_by", "sort_order"]

    @field_validator('group_by')
    def group_by_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GROUP_BY_UNSPECIFIED', 'GROUP_BY_RECENTLY_FOLLOWED', 'GROUP_BY_DEFINITION_NAME', 'GROUP_BY_DATASOURCE_LABEL']):
            raise ValueError("must be one of enum values ('GROUP_BY_UNSPECIFIED', 'GROUP_BY_RECENTLY_FOLLOWED', 'GROUP_BY_DEFINITION_NAME', 'GROUP_BY_DATASOURCE_LABEL')")
        return value

    @field_validator('sort_order')
    def sort_order_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SORT_ORDER_UNSPECIFIED', 'SORT_ORDER_ASCENDING', 'SORT_ORDER_DESCENDING']):
            raise ValueError("must be one of enum values ('SORT_ORDER_UNSPECIFIED', 'SORT_ORDER_ASCENDING', 'SORT_ORDER_DESCENDING')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauPulseSubscriptionserviceTypesV1MetricGroupingPreferences from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauPulseSubscriptionserviceTypesV1MetricGroupingPreferences from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "group_by": obj.get("group_by"),
            "sort_order": obj.get("sort_order")
        })
        return _obj


