# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_metricqueryservice_types_v1_metric_goals import TableauMetricqueryserviceTypesV1MetricGoals
from openapi_client.models.tableau_metricqueryservice_types_v1_metric_specification import TableauMetricqueryserviceTypesV1MetricSpecification
from typing import Optional, Set
from typing_extensions import Self

class TableauMetricqueryserviceV1UpdateMetricRequest(BaseModel):
    """
    TableauMetricqueryserviceV1UpdateMetricRequest
    """ # noqa: E501
    metric_id: Optional[StrictStr] = None
    specification: Optional[TableauMetricqueryserviceTypesV1MetricSpecification] = None
    goals: Optional[TableauMetricqueryserviceTypesV1MetricGoals] = None
    __properties: ClassVar[List[str]] = ["metric_id", "specification", "goals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceV1UpdateMetricRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of specification
        if self.specification:
            _dict['specification'] = self.specification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of goals
        if self.goals:
            _dict['goals'] = self.goals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceV1UpdateMetricRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metric_id": obj.get("metric_id"),
            "specification": TableauMetricqueryserviceTypesV1MetricSpecification.from_dict(obj["specification"]) if obj.get("specification") is not None else None,
            "goals": TableauMetricqueryserviceTypesV1MetricGoals.from_dict(obj["goals"]) if obj.get("goals") is not None else None
        })
        return _obj


