# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_pulse_insightsservice_v1_generate_insight_bundle_response import TableauPulseInsightsserviceV1GenerateInsightBundleResponse
from typing import Optional, Set
from typing_extensions import Self

class TableauPulseInsightsserviceV1GenerateInsightBundleSpringboardResponse(BaseModel):
    """
    TableauPulseInsightsserviceV1GenerateInsightBundleSpringboardResponse
    """ # noqa: E501
    bundle_response: Optional[TableauPulseInsightsserviceV1GenerateInsightBundleResponse] = None
    __properties: ClassVar[List[str]] = ["bundle_response"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauPulseInsightsserviceV1GenerateInsightBundleSpringboardResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bundle_response
        if self.bundle_response:
            _dict['bundle_response'] = self.bundle_response.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauPulseInsightsserviceV1GenerateInsightBundleSpringboardResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bundle_response": TableauPulseInsightsserviceV1GenerateInsightBundleResponse.from_dict(obj["bundle_response"]) if obj.get("bundle_response") is not None else None
        })
        return _obj


