# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_metricqueryservice_types_v1_comparisons_comparison import TableauMetricqueryserviceTypesV1ComparisonsComparison
from typing import Optional, Set
from typing_extensions import Self

class TableauMetricqueryserviceTypesV1Comparisons(BaseModel):
    """
    TableauMetricqueryserviceTypesV1Comparisons
    """ # noqa: E501
    comparisons: Optional[List[TableauMetricqueryserviceTypesV1ComparisonsComparison]] = None
    nested_comparison: Optional[Dict[str, Any]] = Field(default=None, alias="nestedComparison")
    __properties: ClassVar[List[str]] = ["comparisons", "nestedComparison"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceTypesV1Comparisons from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in comparisons (list)
        _items = []
        if self.comparisons:
            for _item_comparisons in self.comparisons:
                if _item_comparisons:
                    _items.append(_item_comparisons.to_dict())
            _dict['comparisons'] = _items
        # override the default output from pydantic by calling `to_dict()` of nested_comparison
        if self.nested_comparison:
            _dict['nestedComparison'] = self.nested_comparison.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauMetricqueryserviceTypesV1Comparisons from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comparisons": [TableauMetricqueryserviceTypesV1ComparisonsComparison.from_dict(_item) for _item in obj["comparisons"]] if obj.get("comparisons") is not None else None,
            "nestedComparison": TableauMetricqueryserviceTypesV1ComparisonsComparison.from_dict(obj["nestedComparison"]) if obj.get("nestedComparison") is not None else None
        })
        return _obj


