# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.tableau_permissionservice_v1_member_error import TableauPermissionserviceV1MemberError
from openapi_client.models.tableau_permissionservice_v1_member_permission import TableauPermissionserviceV1MemberPermission
from typing import Optional, Set
from typing_extensions import Self

class TableauPermissionserviceV1AddDefinitionPermissionsResponse(BaseModel):
    """
    TableauPermissionserviceV1AddDefinitionPermissionsResponse
    """ # noqa: E501
    definition_id: Optional[StrictStr] = None
    member_permissions: Optional[List[TableauPermissionserviceV1MemberPermission]] = None
    member_errors: Optional[List[TableauPermissionserviceV1MemberError]] = None
    __properties: ClassVar[List[str]] = ["definition_id", "member_permissions", "member_errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableauPermissionserviceV1AddDefinitionPermissionsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in member_permissions (list)
        _items = []
        if self.member_permissions:
            for _item_member_permissions in self.member_permissions:
                if _item_member_permissions:
                    _items.append(_item_member_permissions.to_dict())
            _dict['member_permissions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in member_errors (list)
        _items = []
        if self.member_errors:
            for _item_member_errors in self.member_errors:
                if _item_member_errors:
                    _items.append(_item_member_errors.to_dict())
            _dict['member_errors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableauPermissionserviceV1AddDefinitionPermissionsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "definition_id": obj.get("definition_id"),
            "member_permissions": [TableauPermissionserviceV1MemberPermission.from_dict(_item) for _item in obj["member_permissions"]] if obj.get("member_permissions") is not None else None,
            "member_errors": [TableauPermissionserviceV1MemberError.from_dict(_item) for _item in obj["member_errors"]] if obj.get("member_errors") is not None else None
        })
        return _obj


