# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_register_identity_pool_request import TableauAuthnV1RegisterIdentityPoolRequest

class TestTableauAuthnV1RegisterIdentityPoolRequest(unittest.TestCase):
    """TableauAuthnV1RegisterIdentityPoolRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1RegisterIdentityPoolRequest:
        """Test TableauAuthnV1RegisterIdentityPoolRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1RegisterIdentityPoolRequest`
        """
        model = TableauAuthnV1RegisterIdentityPoolRequest()
        if include_optional:
            return TableauAuthnV1RegisterIdentityPoolRequest(
                name = '',
                identity_store_instance = 56,
                auth_type_instance = 56,
                is_enabled = True,
                description = ''
            )
        else:
            return TableauAuthnV1RegisterIdentityPoolRequest(
        )
        """

    def testTableauAuthnV1RegisterIdentityPoolRequest(self):
        """Test TableauAuthnV1RegisterIdentityPoolRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
