# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_pulse_subscription_service_batch_create_subscriptions(self) -> None:
        """Test case for pulse_subscription_service_batch_create_subscriptions

        Creates multiple subscriptions.
        """
        pass

    def test_pulse_subscription_service_batch_get_metric_follower_counts(self) -> None:
        """Test case for pulse_subscription_service_batch_get_metric_follower_counts

        Gets the total number of unique followers per metric
        """
        pass

    def test_pulse_subscription_service_batch_get_subscriptions(self) -> None:
        """Test case for pulse_subscription_service_batch_get_subscriptions

        Gets a batch of subscriptions available on a server.
        """
        pass

    def test_pulse_subscription_service_create_subscription(self) -> None:
        """Test case for pulse_subscription_service_create_subscription

        Creates a subscription.
        """
        pass

    def test_pulse_subscription_service_delete_subscription(self) -> None:
        """Test case for pulse_subscription_service_delete_subscription

        Deletes a subscription.
        """
        pass

    def test_pulse_subscription_service_get_subscription(self) -> None:
        """Test case for pulse_subscription_service_get_subscription

        Gets a subscription based on the specified id.
        """
        pass

    def test_pulse_subscription_service_get_user_digest_preferences(self) -> None:
        """Test case for pulse_subscription_service_get_user_digest_preferences

        Get user digest preferences
        """
        pass

    def test_pulse_subscription_service_get_user_preferences(self) -> None:
        """Test case for pulse_subscription_service_get_user_preferences

        Get user preferences
        """
        pass

    def test_pulse_subscription_service_list_subscriptions(self) -> None:
        """Test case for pulse_subscription_service_list_subscriptions

        Lists the subscriptions available on a server.
        """
        pass

    def test_pulse_subscription_service_update_subscription(self) -> None:
        """Test case for pulse_subscription_service_update_subscription

        Updates a subscription.
        """
        pass

    def test_pulse_subscription_service_update_user_digest_preferences(self) -> None:
        """Test case for pulse_subscription_service_update_user_digest_preferences

        Update user digest preferences
        """
        pass

    def test_pulse_subscription_service_update_user_preferences(self) -> None:
        """Test case for pulse_subscription_service_update_user_preferences

        Update user preferences
        """
        pass


if __name__ == '__main__':
    unittest.main()
