# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_eventservice_types_v1_serialized_event import TableauEventserviceTypesV1SerializedEvent

class TestTableauEventserviceTypesV1SerializedEvent(unittest.TestCase):
    """TableauEventserviceTypesV1SerializedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauEventserviceTypesV1SerializedEvent:
        """Test TableauEventserviceTypesV1SerializedEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauEventserviceTypesV1SerializedEvent`
        """
        model = TableauEventserviceTypesV1SerializedEvent()
        if include_optional:
            return TableauEventserviceTypesV1SerializedEvent(
                id = '',
                type = '',
                user_id = 56,
                site_id = 56,
                session_id = '',
                timestamp = '',
                details = '',
                site_luid = '',
                user_luid = ''
            )
        else:
            return TableauEventserviceTypesV1SerializedEvent(
        )
        """

    def testTableauEventserviceTypesV1SerializedEvent(self):
        """Test TableauEventserviceTypesV1SerializedEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
