# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_pulse_subscriptionservice_v1_get_subscription_response import TableauPulseSubscriptionserviceV1GetSubscriptionResponse

class TestTableauPulseSubscriptionserviceV1GetSubscriptionResponse(unittest.TestCase):
    """TableauPulseSubscriptionserviceV1GetSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPulseSubscriptionserviceV1GetSubscriptionResponse:
        """Test TableauPulseSubscriptionserviceV1GetSubscriptionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPulseSubscriptionserviceV1GetSubscriptionResponse`
        """
        model = TableauPulseSubscriptionserviceV1GetSubscriptionResponse()
        if include_optional:
            return TableauPulseSubscriptionserviceV1GetSubscriptionResponse(
                subscription = openapi_client.models.tableau/pulse/subscriptionservice/types/v1/subscription.tableau.pulse.subscriptionservice.types.v1.Subscription(
                    id = '', 
                    metric_id = '', 
                    follower = openapi_client.models.tableau/pulse/subscriptionservice/types/v1/follower.tableau.pulse.subscriptionservice.types.v1.Follower(
                        user_id = '', 
                        group_id = '', ), 
                    create_time = '', 
                    update_time = '', )
            )
        else:
            return TableauPulseSubscriptionserviceV1GetSubscriptionResponse(
        )
        """

    def testTableauPulseSubscriptionserviceV1GetSubscriptionResponse(self):
        """Test TableauPulseSubscriptionserviceV1GetSubscriptionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
