# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_pulse_subscriptionservice_v1_update_subscription_request import TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest

class TestTableauPulseSubscriptionserviceV1UpdateSubscriptionRequest(unittest.TestCase):
    """TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest:
        """Test TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest`
        """
        model = TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest()
        if include_optional:
            return TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest(
                id = '',
                metric_id = '',
                follower = openapi_client.models.tableau/pulse/subscriptionservice/types/v1/follower.tableau.pulse.subscriptionservice.types.v1.Follower(
                    user_id = '', 
                    group_id = '', )
            )
        else:
            return TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest(
        )
        """

    def testTableauPulseSubscriptionserviceV1UpdateSubscriptionRequest(self):
        """Test TableauPulseSubscriptionserviceV1UpdateSubscriptionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
