# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_identity_store_instance import TableauAuthnV1IdentityStoreInstance

class TestTableauAuthnV1IdentityStoreInstance(unittest.TestCase):
    """TableauAuthnV1IdentityStoreInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1IdentityStoreInstance:
        """Test TableauAuthnV1IdentityStoreInstance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1IdentityStoreInstance`
        """
        model = TableauAuthnV1IdentityStoreInstance()
        if include_optional:
            return TableauAuthnV1IdentityStoreInstance(
                id = 56,
                type = 'LOCAL',
                name = '',
                display_name = '',
                created_at = '',
                updated_at = ''
            )
        else:
            return TableauAuthnV1IdentityStoreInstance(
        )
        """

    def testTableauAuthnV1IdentityStoreInstance(self):
        """Test TableauAuthnV1IdentityStoreInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
