# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_update_identity_pool_request import TableauAuthnV1UpdateIdentityPoolRequest

class TestTableauAuthnV1UpdateIdentityPoolRequest(unittest.TestCase):
    """TableauAuthnV1UpdateIdentityPoolRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1UpdateIdentityPoolRequest:
        """Test TableauAuthnV1UpdateIdentityPoolRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1UpdateIdentityPoolRequest`
        """
        model = TableauAuthnV1UpdateIdentityPoolRequest()
        if include_optional:
            return TableauAuthnV1UpdateIdentityPoolRequest(
                uuid = '',
                name = '',
                is_enabled = True,
                description = ''
            )
        else:
            return TableauAuthnV1UpdateIdentityPoolRequest(
        )
        """

    def testTableauAuthnV1UpdateIdentityPoolRequest(self):
        """Test TableauAuthnV1UpdateIdentityPoolRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
