# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_metricqueryservice_types_v1_representation_options_row_level_entity_names import TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames

class TestTableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames(unittest.TestCase):
    """TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames:
        """Test TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames`
        """
        model = TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames()
        if include_optional:
            return TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames(
                entity_name_singular = '',
                entity_name_plural = ''
            )
        else:
            return TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames(
        )
        """

    def testTableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames(self):
        """Test TableauMetricqueryserviceTypesV1RepresentationOptionsRowLevelEntityNames"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
