# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_metricqueryservice_v1_batch_get_definitions_by_post_request import TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest

class TestTableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest(unittest.TestCase):
    """TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest:
        """Test TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest`
        """
        model = TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest()
        if include_optional:
            return TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest(
                definition_ids = [
                    ''
                    ],
                view = 'DEFINITION_VIEW_UNSPECIFIED',
                number_of_metrics = 56
            )
        else:
            return TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest(
        )
        """

    def testTableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest(self):
        """Test TableauMetricqueryserviceV1BatchGetDefinitionsByPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
