# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.metric_insights_api import MetricInsightsApi


class TestMetricInsightsApi(unittest.TestCase):
    """MetricInsightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricInsightsApi()

    def tearDown(self) -> None:
        pass

    def test_pulse_insights_service_generate_insight_bundle_ban(self) -> None:
        """Test case for pulse_insights_service_generate_insight_bundle_ban

        Generates a BAN insight bundle.
        """
        pass

    def test_pulse_insights_service_generate_insight_bundle_detail(self) -> None:
        """Test case for pulse_insights_service_generate_insight_bundle_detail

        Generates a detail insight bundle.
        """
        pass

    def test_pulse_insights_service_generate_insight_bundle_springboard(self) -> None:
        """Test case for pulse_insights_service_generate_insight_bundle_springboard

        Generates a springboard insight bundle.
        """
        pass


if __name__ == '__main__':
    unittest.main()
