# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_nlp_lens_publicrest_v1_recommended_visualization import TableauNlpLensPublicrestV1RecommendedVisualization

class TestTableauNlpLensPublicrestV1RecommendedVisualization(unittest.TestCase):
    """TableauNlpLensPublicrestV1RecommendedVisualization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauNlpLensPublicrestV1RecommendedVisualization:
        """Test TableauNlpLensPublicrestV1RecommendedVisualization
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauNlpLensPublicrestV1RecommendedVisualization`
        """
        model = TableauNlpLensPublicrestV1RecommendedVisualization()
        if include_optional:
            return TableauNlpLensPublicrestV1RecommendedVisualization(
                expression = '',
                interpretation = '',
                colloquial_alias = ''
            )
        else:
            return TableauNlpLensPublicrestV1RecommendedVisualization(
        )
        """

    def testTableauNlpLensPublicrestV1RecommendedVisualization(self):
        """Test TableauNlpLensPublicrestV1RecommendedVisualization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
