# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_nlp_lens_publicrest_v1_lens_field import TableauNlpLensPublicrestV1LensField

class TestTableauNlpLensPublicrestV1LensField(unittest.TestCase):
    """TableauNlpLensPublicrestV1LensField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauNlpLensPublicrestV1LensField:
        """Test TableauNlpLensPublicrestV1LensField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauNlpLensPublicrestV1LensField`
        """
        model = TableauNlpLensPublicrestV1LensField()
        if include_optional:
            return TableauNlpLensPublicrestV1LensField(
                graph_id = '',
                custom_label = '',
                custom_description = '',
                field_synonyms = [
                    ''
                    ],
                inherited_field_synonyms = [
                    ''
                    ],
                value_synonyms = [
                    openapi_client.models.tableau/nlp/lens/publicrest/v1/value_synonym.tableau.nlp.lens.publicrest.v1.ValueSynonym(
                        value = '', 
                        synonyms = [
                            ''
                            ], )
                    ],
                inherited_value_synonyms = [
                    openapi_client.models.tableau/nlp/lens/publicrest/v1/value_synonym.tableau.nlp.lens.publicrest.v1.ValueSynonym(
                        value = '', 
                        synonyms = [
                            ''
                            ], )
                    ]
            )
        else:
            return TableauNlpLensPublicrestV1LensField(
        )
        """

    def testTableauNlpLensPublicrestV1LensField(self):
        """Test TableauNlpLensPublicrestV1LensField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
