# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_update_auth_configuration_request import TableauAuthnV1UpdateAuthConfigurationRequest

class TestTableauAuthnV1UpdateAuthConfigurationRequest(unittest.TestCase):
    """TableauAuthnV1UpdateAuthConfigurationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1UpdateAuthConfigurationRequest:
        """Test TableauAuthnV1UpdateAuthConfigurationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1UpdateAuthConfigurationRequest`
        """
        model = TableauAuthnV1UpdateAuthConfigurationRequest()
        if include_optional:
            return TableauAuthnV1UpdateAuthConfigurationRequest(
                id = 56,
                auth_type = 'OIDC',
                iframed_idp_enabled = True,
                oidc = openapi_client.models.tableau/authn/v1/oidc_config.tableau.authn.v1.OidcConfig(
                    client_id = '', 
                    client_secret = '', 
                    config_url = '', 
                    custom_scope = '', 
                    id_claim = '', 
                    username_claim = '', 
                    client_authentication = '', 
                    essential_acr_values = '', 
                    voluntary_acr_values = '', 
                    prompt = '', 
                    connection_timeout = 56, 
                    read_timeout = 56, 
                    ignore_domain = True, 
                    ignore_jwk = True, )
            )
        else:
            return TableauAuthnV1UpdateAuthConfigurationRequest(
        )
        """

    def testTableauAuthnV1UpdateAuthConfigurationRequest(self):
        """Test TableauAuthnV1UpdateAuthConfigurationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
