# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_pulse_insightsservice_v1_row_entry import TableauPulseInsightsserviceV1RowEntry

class TestTableauPulseInsightsserviceV1RowEntry(unittest.TestCase):
    """TableauPulseInsightsserviceV1RowEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPulseInsightsserviceV1RowEntry:
        """Test TableauPulseInsightsserviceV1RowEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPulseInsightsserviceV1RowEntry`
        """
        model = TableauPulseInsightsserviceV1RowEntry()
        if include_optional:
            return TableauPulseInsightsserviceV1RowEntry(
                formatted_value = ''
            )
        else:
            return TableauPulseInsightsserviceV1RowEntry(
        )
        """

    def testTableauPulseInsightsserviceV1RowEntry(self):
        """Test TableauPulseInsightsserviceV1RowEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
