# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_metricqueryservice_types_v1_metadata_user import TableauMetricqueryserviceTypesV1MetadataUser

class TestTableauMetricqueryserviceTypesV1MetadataUser(unittest.TestCase):
    """TableauMetricqueryserviceTypesV1MetadataUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauMetricqueryserviceTypesV1MetadataUser:
        """Test TableauMetricqueryserviceTypesV1MetadataUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauMetricqueryserviceTypesV1MetadataUser`
        """
        model = TableauMetricqueryserviceTypesV1MetadataUser()
        if include_optional:
            return TableauMetricqueryserviceTypesV1MetadataUser(
                id = ''
            )
        else:
            return TableauMetricqueryserviceTypesV1MetadataUser(
        )
        """

    def testTableauMetricqueryserviceTypesV1MetadataUser(self):
        """Test TableauMetricqueryserviceTypesV1MetadataUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
