# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_pulse_subscriptionservice_types_v1_follower import TableauPulseSubscriptionserviceTypesV1Follower

class TestTableauPulseSubscriptionserviceTypesV1Follower(unittest.TestCase):
    """TableauPulseSubscriptionserviceTypesV1Follower unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPulseSubscriptionserviceTypesV1Follower:
        """Test TableauPulseSubscriptionserviceTypesV1Follower
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPulseSubscriptionserviceTypesV1Follower`
        """
        model = TableauPulseSubscriptionserviceTypesV1Follower()
        if include_optional:
            return TableauPulseSubscriptionserviceTypesV1Follower(
                user_id = '',
                group_id = ''
            )
        else:
            return TableauPulseSubscriptionserviceTypesV1Follower(
        )
        """

    def testTableauPulseSubscriptionserviceTypesV1Follower(self):
        """Test TableauPulseSubscriptionserviceTypesV1Follower"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
