# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_list_identity_stores_response import TableauAuthnV1ListIdentityStoresResponse

class TestTableauAuthnV1ListIdentityStoresResponse(unittest.TestCase):
    """TableauAuthnV1ListIdentityStoresResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1ListIdentityStoresResponse:
        """Test TableauAuthnV1ListIdentityStoresResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1ListIdentityStoresResponse`
        """
        model = TableauAuthnV1ListIdentityStoresResponse()
        if include_optional:
            return TableauAuthnV1ListIdentityStoresResponse(
                instances = [
                    openapi_client.models.tableau/authn/v1/identity_store_instance.tableau.authn.v1.IdentityStoreInstance(
                        id = 56, 
                        type = 'LOCAL', 
                        name = '', 
                        display_name = '', 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return TableauAuthnV1ListIdentityStoresResponse(
        )
        """

    def testTableauAuthnV1ListIdentityStoresResponse(self):
        """Test TableauAuthnV1ListIdentityStoresResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
