# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_oidc_config import TableauAuthnV1OidcConfig

class TestTableauAuthnV1OidcConfig(unittest.TestCase):
    """TableauAuthnV1OidcConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1OidcConfig:
        """Test TableauAuthnV1OidcConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1OidcConfig`
        """
        model = TableauAuthnV1OidcConfig()
        if include_optional:
            return TableauAuthnV1OidcConfig(
                client_id = '',
                client_secret = '',
                config_url = '',
                custom_scope = '',
                id_claim = '',
                username_claim = '',
                client_authentication = '',
                essential_acr_values = '',
                voluntary_acr_values = '',
                prompt = '',
                connection_timeout = 56,
                read_timeout = 56,
                ignore_domain = True,
                ignore_jwk = True
            )
        else:
            return TableauAuthnV1OidcConfig(
        )
        """

    def testTableauAuthnV1OidcConfig(self):
        """Test TableauAuthnV1OidcConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
