# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_metricqueryservice_types_v1_datasource import TableauMetricqueryserviceTypesV1Datasource

class TestTableauMetricqueryserviceTypesV1Datasource(unittest.TestCase):
    """TableauMetricqueryserviceTypesV1Datasource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauMetricqueryserviceTypesV1Datasource:
        """Test TableauMetricqueryserviceTypesV1Datasource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauMetricqueryserviceTypesV1Datasource`
        """
        model = TableauMetricqueryserviceTypesV1Datasource()
        if include_optional:
            return TableauMetricqueryserviceTypesV1Datasource(
                id = ''
            )
        else:
            return TableauMetricqueryserviceTypesV1Datasource(
        )
        """

    def testTableauMetricqueryserviceTypesV1Datasource(self):
        """Test TableauMetricqueryserviceTypesV1Datasource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
