# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_pulse_insightsservice_v1_goals import TableauPulseInsightsserviceV1Goals

class TestTableauPulseInsightsserviceV1Goals(unittest.TestCase):
    """TableauPulseInsightsserviceV1Goals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPulseInsightsserviceV1Goals:
        """Test TableauPulseInsightsserviceV1Goals
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPulseInsightsserviceV1Goals`
        """
        model = TableauPulseInsightsserviceV1Goals()
        if include_optional:
            return TableauPulseInsightsserviceV1Goals(
                target = openapi_client.models.tableau/metricqueryservice/types/v1/target_value_goal.tableau.metricqueryservice.types.v1.TargetValueGoal(
                    value = 1.337, )
            )
        else:
            return TableauPulseInsightsserviceV1Goals(
        )
        """

    def testTableauPulseInsightsserviceV1Goals(self):
        """Test TableauPulseInsightsserviceV1Goals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
