# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_permissionservice_v1_member_error import TableauPermissionserviceV1MemberError

class TestTableauPermissionserviceV1MemberError(unittest.TestCase):
    """TableauPermissionserviceV1MemberError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauPermissionserviceV1MemberError:
        """Test TableauPermissionserviceV1MemberError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauPermissionserviceV1MemberError`
        """
        model = TableauPermissionserviceV1MemberError()
        if include_optional:
            return TableauPermissionserviceV1MemberError(
                member_id = '',
                member_entity_type = 'MEMBER_ENTITY_TYPE_UNSPECIFIED',
                error_id = '',
                error_message = ''
            )
        else:
            return TableauPermissionserviceV1MemberError(
        )
        """

    def testTableauPermissionserviceV1MemberError(self):
        """Test TableauPermissionserviceV1MemberError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
