# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.custom_domains_api import CustomDomainsApi


class TestCustomDomainsApi(unittest.TestCase):
    """CustomDomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomDomainsApi()

    def tearDown(self) -> None:
        pass

    def test_custom_domains_service_create_site_custom_domain_settings(self) -> None:
        """Test case for custom_domains_service_create_site_custom_domain_settings

        Create custom domain settings
        """
        pass

    def test_custom_domains_service_delete_site_custom_domain_settings(self) -> None:
        """Test case for custom_domains_service_delete_site_custom_domain_settings

        Delete custom domain settings
        """
        pass

    def test_custom_domains_service_get_site_custom_domain(self) -> None:
        """Test case for custom_domains_service_get_site_custom_domain

        Get Custom Domain Name
        """
        pass

    def test_custom_domains_service_get_site_custom_domain_settings(self) -> None:
        """Test case for custom_domains_service_get_site_custom_domain_settings

        Get custom domain settings
        """
        pass

    def test_custom_domains_service_update_site_custom_domain_settings(self) -> None:
        """Test case for custom_domains_service_update_site_custom_domain_settings

        Update custom domain settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
