# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_eventservice_v1_event_input import TableauEventserviceV1EventInput

class TestTableauEventserviceV1EventInput(unittest.TestCase):
    """TableauEventserviceV1EventInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauEventserviceV1EventInput:
        """Test TableauEventserviceV1EventInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauEventserviceV1EventInput`
        """
        model = TableauEventserviceV1EventInput()
        if include_optional:
            return TableauEventserviceV1EventInput(
                type = '',
                details = ''
            )
        else:
            return TableauEventserviceV1EventInput(
        )
        """

    def testTableauEventserviceV1EventInput(self):
        """Test TableauEventserviceV1EventInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
