# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_analyticsextensions_v1_connection_metadata import TableauAnalyticsextensionsV1ConnectionMetadata

class TestTableauAnalyticsextensionsV1ConnectionMetadata(unittest.TestCase):
    """TableauAnalyticsextensionsV1ConnectionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAnalyticsextensionsV1ConnectionMetadata:
        """Test TableauAnalyticsextensionsV1ConnectionMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAnalyticsextensionsV1ConnectionMetadata`
        """
        model = TableauAnalyticsextensionsV1ConnectionMetadata()
        if include_optional:
            return TableauAnalyticsextensionsV1ConnectionMetadata(
                connection_luid = '',
                connection_brief = openapi_client.models.tableau/analyticsextensions/v1/connection_brief.tableau.analyticsextensions.v1.ConnectionBrief(
                    connection_name = '', 
                    connection_type = 'UNDEFINED', )
            )
        else:
            return TableauAnalyticsextensionsV1ConnectionMetadata(
        )
        """

    def testTableauAnalyticsextensionsV1ConnectionMetadata(self):
        """Test TableauAnalyticsextensionsV1ConnectionMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
