# coding: utf-8

"""
    Tableau Services APIs

    Open API specification for Tableau Services APIs

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tableau_authn_v1_register_identity_store_request import TableauAuthnV1RegisterIdentityStoreRequest

class TestTableauAuthnV1RegisterIdentityStoreRequest(unittest.TestCase):
    """TableauAuthnV1RegisterIdentityStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableauAuthnV1RegisterIdentityStoreRequest:
        """Test TableauAuthnV1RegisterIdentityStoreRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableauAuthnV1RegisterIdentityStoreRequest`
        """
        model = TableauAuthnV1RegisterIdentityStoreRequest()
        if include_optional:
            return TableauAuthnV1RegisterIdentityStoreRequest(
                type = 'LOCAL',
                name = '',
                display_name = ''
            )
        else:
            return TableauAuthnV1RegisterIdentityStoreRequest(
        )
        """

    def testTableauAuthnV1RegisterIdentityStoreRequest(self):
        """Test TableauAuthnV1RegisterIdentityStoreRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
