
from enum import Enum


class TableauAggregation(Enum):
    SUM = "AGGREGATION_SUM"
    AVERAGE = "AGGREGATION_AVERAGE"
    MEDIAN = "AGGREGATION_MEDIAN"
    MAX = "AGGREGATION_MAX"
    MIN = "AGGREGATION_MIN"
    COUNT = "AGGREGATION_COUNT"
    COUNT_DISTINCT = "AGGREGATION_COUNT_DISTINCT"

class TableauGranularity(Enum):
    YEAR= "GRANULARITY_BY_YEAR"
    QUARTER = "GRANULARITY_BY_QUARTER"
    MONTH = "GRANULARITY_BY_MONTH"
    WEEK = "GRANULARITY_BY_WEEK"
    DAY = "GRANULARITY_BY_DAY"

class PulseMetric:
    pass